### ISSUE TITLE
A few minor things

### ISSUE THREAD

**Issue by sy2002** [Kugelblitz360/C64MEGA65DOCS#1]
### 1) You are using the Slack icon instead of the Discord icon:

<img width="447" alt="grafik" src="https://github.com/user-attachments/assets/442990d4-6646-400e-9a5b-030206bf23a0">

### 2) Start page https://kugelblitz360.github.io/C64MEGA65DOCS/c64formega65.html:

"Read more about this in the [Testing](https://kugelblitz360.github.io/C64MEGA65DOCS/testing.html) section of this manual."   The "Testing" link leads to nowhere.

### 3) Resetting the core has a duplicate-ish paragraph:

> The same will happen if you press the Reset button on the left side of the MEGA65 briefly (less than 1.5 seconds) - we call this a Soft Reset. If you press it longer, you will do a Hard Reset

> If you press the reset button of your MEGA65 briefly, i.e. less than 1.5 seconds, you will do a soft-reset. A long press does a hard-reset. Here is the difference between the two:

### 4) Everywhere throughout the documentation:

In German, people very often said "Modul" when they meant "Cartridge". This is why German native speakers often translate "Cartridge" to "Module" which is misleading to English native speakers. Suggestion: Use "Cartrige" instead of "Module".

### 5) https://kugelblitz360.github.io/C64MEGA65DOCS/working-with-disks-and-drives.html :

* I would not call it a "rudimentary implementation" as it simulates the built in 6502 and all the chips and therefore supports fast loaders and even demos that use the drive as co-processor. "Rudimentary" is something different :-)

* There is a space missing in this sentence fragment: "in.g64format."

### 6) https://kugelblitz360.github.io/C64MEGA65DOCS/saving-data-with-the-c64-core.html

Actually this is not necessary:

> Please Hard Reset the Core before changing SD Card.

In contrast: The file browser even in real time detects if you change the SD card while it is open. It is completely safe and pro-actively supported by the core.

Here is the rule: As long as the drive led is **not yellow** and you do not plan to save anything to a currently mounted `*.d64` disk image then it is save to fiddle around with the SD card. See also: https://github.com/MJoergen/C64MEGA65/blob/develop/FAQ.md#18-what-do-the-two-leds-signal

**Comment by Kugelblitz360** [comment]
1) Will be fixed, the theme I am using only "supports" slack, I just need to replace the icon file before release.

2) Testing will become a real page with some explanation, but links to the dev github for the full lists because we don't want to copy changing development info into the user docs.

3) done

4) I do not understand at all what you are trying to say

5) Well, it does not do .g64 which would be expected by a full implementation. But I rudimentary is the wrong word, I will change that.

6) OK, I was taking the safe side here.

**Comment by sy2002** [comment]
Thanks for the feedback @Kugelblitz360 . Re (4): Suggestion: Change the term "Module" to the term "Cartridge" everywhere you are talking about C64 expansion port cartridges.

**Comment by Kugelblitz360** [comment]
All changes done and there was exactly one "module" in the Reset section which I actually copy and pasted from somewhere else, so that why I was confused. All other pages were modul-free :-)
