### ISSUE TITLE
Working with Disks and drives

### ISSUE THREAD

**Issue by sy2002** [Kugelblitz360/C64MEGA65DOCS#2]
### 1) Mention how to load

A while ago, one particularly "capable" user gave us a bad rating on the file host because he did not know the `LOAD"*",8,1` command as we found out later while chatting on Discord:

<img width="1640" alt="grafik" src="https://github.com/user-attachments/assets/51750835-3dae-4864-acd8-a4f73d33e9ee">

This is why the original doc looks like this: https://github.com/MJoergen/C64MEGA65/tree/master?tab=readme-ov-file#mounting-disk-images

### 2) Some demos or games require disk switching

... which is why it is documented here:
https://github.com/MJoergen/C64MEGA65/tree/master?tab=readme-ov-file#switching-diskettes-while-a-program-is-running

### 3) You can unmount disk images using <kbd>Space</kbd>

... which is documented here: https://github.com/MJoergen/C64MEGA65/tree/master?tab=readme-ov-file#writing-to-disk-images

**Comment by Kugelblitz360** [comment]
Very good remarks, I will add the Load command to the Troubleshooting section though.

**Comment by Kugelblitz360** [comment]
All suggestions included now.
