### ISSUE TITLE
Barcode issue might deserve prominent mention

### ISSUE THREAD

**Issue by sy2002** [Kugelblitz360/C64MEGA65DOCS#3]
I fear, that this issue here https://github.com/MJoergen/C64MEGA65/issues/145 that is documented on Discord here https://discord.com/channels/719326990221574164/801767398675316756/1261683009451462709 might be more prevalent than I hoped. My original assumption that less than 1% of the R6 users are affected might have been to optimistic and in the meantime we have a YouTube video out there that shows the problem to a broader public: https://www.youtube.com/watch?si=dkNWIpwsryi_5LK_&v=n2D2Oix4XlY&feature=youtu.be

We have a permanent download link to a hotfix: https://t.ly/ujcev

Does it make sense to have a very prominent place where we describe the problem, maybe show a screenshot of the issue and then offer the download link? I could add it to the FAQ.md for sure and I also might want to mention this in the FileHost download page, but as we transition to the new docs, we might want to think about this, too. Right now, people are hitting the Discord #c64-core support channel and ask the question and then they are redirected by friendly support people to my above-mentioned "aspirin pain killer" post.

The next official release will take a while, this is why I am thinking out loud about this issue.

**Comment by Kugelblitz360** [comment]
I will add a "Troubleshooting" page that will have this as the very first issue, including screenshot.

**Comment by Kugelblitz360** [comment]
Done in Troubleshooting and FAQ
