### ISSUE TITLE
Proof reading the C64 docs PART #4 (FINAL)

### ISSUE THREAD

**Issue by sy2002** [Kugelblitz360/C64MEGA65DOCS#7]
### Formatting
Please add a short section "Formatting" that explains stuff like this:

Currently we cannot format a simulated disk, i.e. a .d64 disk image. So something like

OPEN1,8,15,"N:NAME,ID":CLOSE1

will not work with the core and this means, that games that do format their own game disks (maybe for save games) with some own fancy format will not work.

This does not contradict that you can use an empty D64 file in most of the cases. It just says that if a game, the user or a BASIC program wants to format the disk by itself, then it will fail.

### SD2IEC and Pi1541

Minor typo: Replace "hardware designs" by "hardware design"

#### Important safety tips

Minor typo: Remove "." behind "Protoparts"

#### MEGA65 revisions and compatibility

Dead link: "Learn more about [different MEGA65 revisions here](https://kugelblitz360.github.io/C64MEGA65DOCS/models.md)." links to nowhere

### C64GS Cartridges

Can you add a link to the main menu's Kernal section for the user's convenience to understand how to switch to the C64GS Kernal?

This request is true for the hardware version of this section as well as the virtual section

### Kernal Replacement Carts (virtual section)

I do not fully get, what you want to say here:

"These is no specification in VICE for external Kernal replacements (EF3 or others). "

Maybe "There" instead of "These"?

## the-1750-ram-expansion-unit.html

When talking about GEOS in the REU context, it might make sense to link to AmokPhazes pretty awesome documentation where he describes how to use GEOS with the C64 core: https://github.com/MJoergen/C64MEGA65/blob/master/doc/GEOS_WITH_THE_C64_CORE.pdf

### Install JiffyDOS for the C64 Core

"(See Core Installation)" ==> Can you link to the appropriate chapter/section?

### Installing other Kernals than JiffyDOS

Minor typo: "yo" => "you"

### Installing other Floppy Speeders

Minor typos:

* "Floppy Speeders that requires an" ==> "require"
* "Kernal Replacements" ==> "replacements"
* "Floppy Speeders" ==> "floppy speeders"

### Hard Reset

* "If you notice that the MEGA65’s “Drive” LED turns blue," ==> actually, it is the POWER LED that turns blue, not the drive led.

* Consistency: "Hard-reset" ==> "Hard Reset" (multiple times in this section)

*  Typo: "C64ore" ==> "C64 core"

## testing.html

"demo disks:" ==> I propose to talk about demos or even Demos not about demo disks

## future-versions-and-roadmap.html

"All code is on GitHub" => maybe you want to link to https://github.com/MJoergen/C64MEGA65

"Just asking in the Discord" ==> remove "the"

### Link more often to other parts of the user's guide

Remember: People jump directly to the FAQ very often, so it is helpful to guide them from here to the the appropriate user's guide sections when explaining what they should do. This is true for a lot of sections of the FAQ.

### Strange picture on a VGA display

* "Please try the Auto Adjust function or similar on your VGA display, especially when switching screen modes or turning HDMI Flicker Free on or off."  => Please be more precise: You actually need to turn Flicker Free OFF when you use VGA

* You are right: When NOT using a bulky CRT then do NOT use 15 KHz but WHEN you DO use a bulky CRT, then you SHOULD use 15 KHz. 

### The built-in freezer does not work

"In the C64 Core this functionality is repeated, " ==> "replicated" instead of "repeated"

### I can not open a specific .d64 file

Minor typo: Add a dot "." at the end of the sentence.

### Can I access the MEGA65 Realtime Clock from the C64 Core?

You might either want to link to 

https://github.com/MJoergen/C64MEGA65/blob/master/doc/RTC.md

or copy/paste infos from there.

### Can I change the color palette of the C64 Core?

For color nerds it might be an interesting additional info, that we actually implemented this carefully measured color scheme:

https://www.pepto.de/projects/colorvic/

### Can the Core run GEOS?

Maybe you copy/paste all the info from here, as it also contains a download link to an appropriate version plus explains the RTC and therefore makes the Geos experience "whole":

https://github.com/MJoergen/C64MEGA65/blob/master/FAQ.md#17-how-can-i-work-with-geos

### Confused about models?

Does it make sense to have something like this in the FAQ?

https://github.com/MJoergen/C64MEGA65/blob/master/FAQ.md#1-which-core-should-i-install-i-am-confused-what-r3r3ar4r5r6-means

### Rare edge case

I am not if it makes sense to add this, please decide:

https://github.com/MJoergen/C64MEGA65/blob/master/FAQ.md#rare-case-zeta-wing-cartridge-is-not-working-maybe-also-relevant-for-other-protovision-cartridges

## Final

This is the final GitHub issue I will raise about proof reading for the time being. As of October 11, 2024 I have proof-read the whole documentation. GREAT JOB! THANK YOU: This moves the whole C64 core user experience to the next level!!

**Comment by Kugelblitz360** [comment]
All comm

**Comment by Kugelblitz360** [comment]
All comments included. Thank you for proofreading!
